### Data Normalization
#### sklearn.preprocesing package

In [16]:
# import the library
import numpy as np

In [22]:
xMatrice = np.matrix('1, -1, 2; 2, 0, 0; 0, 1, -1')

In [23]:
print(xMatrice)

[[ 1 -1  2]
 [ 2  0  0]
 [ 0  1 -1]]
