### Data Normalization
#### sklearn.preprocesing package

In [29]:
# import the libary
import numpy as np
from sklearn import preprocessing as pr

In [30]:
# define the matrix
matriX = np.array([[1, -1, 2], [2, 0, 0], [0, 1, -1]], dtype = int)

print("matrix:\n", matriX)

matrix:
 [[ 1 -1  2]
 [ 2  0  0]
 [ 0  1 -1]]


In [31]:
# media matricei
media = matriX.mean()

print("Mean of matrix:", media)

Mean of matrix: 0.4444444444444444


In [32]:
# variance matricei
variante = matriX.var()

print("Variante of matrix:", variante)

Variante of matrix: 1.1358024691358024


In [44]:
newMatrix = pr.scale(matriX)

print("newMatrix:\n", newMatrix)

newMatrix:
 [[ 0.         -1.22474487  1.33630621]
 [ 1.22474487  0.         -0.26726124]
 [-1.22474487  1.22474487 -1.06904497]]


In [43]:
# media matricei
newMedia = newMatrix.mean()

print("New mean:", newMedia)

New mean: 4.9343245538895844e-17


In [42]:
# variance matricei
newVariante = newMatrix.var()

print("New variante:", newVariante)

New variante: 1.0


## Exemplu Sergei

In [2]:
import numpy as np
from sklearn import preprocessing as pr
X = np.array([[1, -1, 2], [2, 0, 0], [0, 1, -1]], dtype=int)
print(X)
mn = X.mean()
vr = X.var()
print(mn)
print(vr)
X2 = pr.scale(X)
print(X2)
mn2 = X2.mean()
vr2 = X2.var()
print(mn2)
print(vr2)


[[ 1 -1  2]
 [ 2  0  0]
 [ 0  1 -1]]
0.4444444444444444
1.1358024691358024
[[ 0.         -1.22474487  1.33630621]
 [ 1.22474487  0.         -0.26726124]
 [-1.22474487  1.22474487 -1.06904497]]
4.9343245538895844e-17
1.0


In [45]:
# import the libary
import numpy as np
from sklearn import preprocessing as pr

# define the matrix
matriX = np.array([[1, -1, 2], [2, 0, 0], [0, 1, -1]], dtype = int)

print("matrix:\n", matriX)

# media matricei
media = matriX.mean()
print("Mean of matrix:", media)

# variance matricei
variante = matriX.var()
print("Variante of matrix:", variante)

# scalarea matricei
newMatrix = pr.scale(matriX)
print("newMatrix:\n", newMatrix)

# media matricei
newMedia = newMatrix.mean()
print("New mean:", newMedia)


# variance matricei
newVariante = newMatrix.var()
print("New variante:", newVariante)


matrix:
 [[ 1 -1  2]
 [ 2  0  0]
 [ 0  1 -1]]
Mean of matrix: 0.4444444444444444
Variante of matrix: 1.1358024691358024
newMatrix:
 [[ 0.         -1.22474487  1.33630621]
 [ 1.22474487  0.         -0.26726124]
 [-1.22474487  1.22474487 -1.06904497]]
New mean: 4.9343245538895844e-17
New variante: 1.0


Dupa parerea mea după manipulările noastre, diferența dintre valorile minime și maxime
scade și din această cauză, valoarea medie scade. Cu cât dispersia parametrilor modelului este
mai mare, cu atât acesta va fi mai puțin stabil. Varianța a scăzut, ceea ce înseamnă că modelul a
devenit mai stabil.