<a href="https://colab.research.google.com/github/mrbseba/dataVisualization/blob/master/cMinMaxNormalization.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**C Min Max Normalization**
1. Create	the	following matrix	X2:
  
  1, -1, 2,
  
  2, 0, 0,
  
  0, 1, -1
2. Print	the	matrix	and	compute	the	mean	of	the	variables.
3. Normalize the	data	using	MinMaxScaler.	Print	the	scaled	matrix	and	compute	the	mean	and	the	variance.	What	can	you	conclude?

In [4]:
# import library numpyt - for matrix and advance mathematical opereation
import numpy as np

# import library for normalizing
from sklearn.preprocessing import Normalizer

# import the library for MinMaxScaler
from sklearn.preprocessing import MinMaxScaler

In [2]:
# define the matrix
matriX = np.matrix('1, -1, 2; 2, 0, 0; 0, 1, -1') # tuple 
print("matrix:\n", matriX)

matrix:
 [[ 1 -1  2]
 [ 2  0  0]
 [ 0  1 -1]]


In [3]:
# the mena of the variables
media = matriX.mean()
print(media)

0.4444444444444444


In [29]:
# normalize the data usign MinMaxScaler
convertArraytMartix = np.asarray(matriX) # convert to numpay array
print("- listMatrix:\n", convertArraytMartix)

print("\n")
scaler = MinMaxScaler()
print(scaler.fit(convertArraytMartix))

print("\n")

print("dataMax", scaler.data_max_)

print("\n")

scaledMatrix = scaler.transform(convertArraytMartix)
print("Scaled Matrix\n", scaledMatrix)



- listMatrix:
 [[ 1 -1  2]
 [ 2  0  0]
 [ 0  1 -1]]


MinMaxScaler()


dataMax [2. 1. 2.]


Scaled Matrix
 [[0.5        0.         1.        ]
 [1.         0.5        0.33333333]
 [0.         1.         0.        ]]


In [33]:
# the mean of the scaled matrix
scaledMeanMatrix = scaledMatrix.mean()
print("mean of the scaled matrix:", scaledMeanMatrix)

mean of the scaled matrix: 0.48148148148148145


**Concluzi**

Putem obeserva că media la scalarea matricei este mai mare ca media inițială
