<a href="https://colab.research.google.com/github/mrbseba/dataVisualization/blob/master/dataNormalization.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Crate	the		following	matrice X :

  1, -1, 2,
  
  2, 0, 0,
  
  0, 1, -1

2. Print	X	and	compute	the	mean	and	the	variance	of	X.
3. Use	the	scale function	to	normalize	X.	Analyze	the	result.
4. Compute	the	mean	and	the	variance	of	the	scaled X.	What	can	you	conclude?

In [2]:
# import library numpyt - for matrix and advance mathematical opereation
import numpy as np
# import library for normalizing
from sklearn.preprocessing import Normalizer

In [3]:
# define the matrix
matriX = np.matrix('1, -1, 2; 2, 0, 0; 0, 1, -1') # tuple 
print("matrix:\n", matriX)

matrix:
 [[ 1 -1  2]
 [ 2  0  0]
 [ 0  1 -1]]


In [4]:
# media matricei
media = matriX.mean()
print(media)

0.4444444444444444


In [5]:
# variance matricei
variante = matriX.var()
print(variante)

1.1358024691358024


In [6]:
# normalize the matrix
convertArraytMartix = np.asarray(matriX) # convert to numpay array
print("- listMatrix:\n", convertArraytMartix)

transformer = Normalizer().fit(convertArraytMartix)  # fit does nothing.
newMatrix = transformer.transform(convertArraytMartix)

print("\n- normalizeMatrix:")
print(newMatrix)

- listMatrix:
 [[ 1 -1  2]
 [ 2  0  0]
 [ 0  1 -1]]

- normalizeMatrix:
[[ 0.40824829 -0.40824829  0.81649658]
 [ 1.          0.          0.        ]
 [ 0.          0.70710678 -0.70710678]]


In [7]:
newMedia = newMatrix.mean()
print(newMedia)

0.20183295343641403


In [8]:
newVariante = newMedia.var()
print(newVariante)

0.0


**Cuncluzii**

După ce am făcut normalizara putem observa faptul că media nouă est mai joasă decât prima medie iar noua variantie este egala cu *zero*