### MinMaxNormalization

##### An  alternative  standardization  is  scaling  features  to  lie  between  a  given minimum and maximum value, often between zero and one. This can be achieved usingMinMaxScaler.

In [20]:
# import the libary
import numpy as np
from sklearn import preprocessing as pr

# define the matrix
matriX = np.array([[1, -1, 2], [2, 0, 0], [0, 1, -1]], dtype = int)

print("matrix:\n", matriX)

# media matricei
media = matriX.mean()
print("Mean of matrix:", media)


newMatrix = pr.minmax_scale(matriX)
print(newMatrix)
print("newMatrix:\n", newMatrix )


# media matricei
newMedia = newMatrix.mean()
print("New mean:", newMedia)


# variance matricei
newVariante = newMatrix.var()
print("Variante:", newVariante)


matrix:
 [[ 1 -1  2]
 [ 2  0  0]
 [ 0  1 -1]]
Mean of matrix: 0.4444444444444444
[[0.5        0.         1.        ]
 [1.         0.5        0.33333333]
 [0.         1.         0.        ]]
newMatrix:
 [[0.5        0.         1.        ]
 [1.         0.5        0.33333333]
 [0.         1.         0.        ]]
New mean: 0.48148148148148145
Variante: 0.16941015089163236


Media și varianța au scăzut, ceea ce înseamnă că stabilitatea modelului a crescut.
Varianța a scăzut mai mult decât în punct B.